# Matrix Multiplication

$$c_{ij} = a_{i1}b_{1j} + a_{i2}b_{2j} +\cdots + a_{in}b_{nj}= \sum_{k=1}^n a_{ik}b_{kj}$$

To compute the matrix product of two tensors, we need three nested *for loops*. One for columns, one for rows and another for the sum of indices.

We need to check that the number of columns of the first tensor is equals to numbers of rows of the second.

In [3]:
import torch
from torch import Tensor

In [4]:
inputs = torch.randn(10, 1)
weights = torch.randn(1, 10)
bias = torch.randn(10)

In [5]:
def matmul(a, b):
    ar, ac = a.shape
    br, bc = b.shape
    assert ac == br
    c = torch.zeros(ar, bc)
    for k in range(ac):
        for i in range(ar):
            for j in range(bc):
                c[i, j] += a[i, k] * b[k, j]
    return c

In [10]:
matmul(inputs, weights)

tensor([[-0.0362,  0.4280,  0.2312,  0.0494, -0.7850,  0.1298, -0.1876, -0.0763,
          0.0612,  0.2624],
        [ 0.0912, -1.0788, -0.5828, -0.1245,  1.9788, -0.3271,  0.4728,  0.1924,
         -0.1543, -0.6615],
        [-0.0121,  0.1426,  0.0771,  0.0165, -0.2617,  0.0433, -0.0625, -0.0254,
          0.0204,  0.0875],
        [ 0.0376, -0.4444, -0.2401, -0.0513,  0.8153, -0.1348,  0.1948,  0.0793,
         -0.0636, -0.2725],
        [-0.1378,  1.6296,  0.8804,  0.1880, -2.9892,  0.4942, -0.7142, -0.2907,
          0.2331,  0.9992],
        [ 0.0843, -0.9966, -0.5384, -0.1150,  1.8281, -0.3022,  0.4368,  0.1778,
         -0.1426, -0.6111],
        [ 0.0059, -0.0696, -0.0376, -0.0080,  0.1277, -0.0211,  0.0305,  0.0124,
         -0.0100, -0.0427],
        [ 0.0574, -0.6788, -0.3667, -0.0783,  1.2451, -0.2058,  0.2975,  0.1211,
         -0.0971, -0.4162],
        [ 0.0159, -0.1884, -0.1018, -0.0217,  0.3456, -0.0571,  0.0826,  0.0336,
         -0.0270, -0.1155],
        [ 0.0040, -

### Python matmul

In [16]:
inputs @ weights

tensor([[-0.0362,  0.4280,  0.2312,  0.0494, -0.7850,  0.1298, -0.1876, -0.0763,
          0.0612,  0.2624],
        [ 0.0912, -1.0788, -0.5828, -0.1245,  1.9788, -0.3271,  0.4728,  0.1924,
         -0.1543, -0.6615],
        [-0.0121,  0.1426,  0.0771,  0.0165, -0.2617,  0.0433, -0.0625, -0.0254,
          0.0204,  0.0875],
        [ 0.0376, -0.4444, -0.2401, -0.0513,  0.8153, -0.1348,  0.1948,  0.0793,
         -0.0636, -0.2725],
        [-0.1378,  1.6296,  0.8804,  0.1880, -2.9892,  0.4942, -0.7142, -0.2907,
          0.2331,  0.9992],
        [ 0.0843, -0.9966, -0.5384, -0.1150,  1.8281, -0.3022,  0.4368,  0.1778,
         -0.1426, -0.6111],
        [ 0.0059, -0.0696, -0.0376, -0.0080,  0.1277, -0.0211,  0.0305,  0.0124,
         -0.0100, -0.0427],
        [ 0.0574, -0.6788, -0.3667, -0.0783,  1.2451, -0.2058,  0.2975,  0.1211,
         -0.0971, -0.4162],
        [ 0.0159, -0.1884, -0.1018, -0.0217,  0.3456, -0.0571,  0.0826,  0.0336,
         -0.0270, -0.1155],
        [ 0.0040, -

### PyTorch matmul

In [17]:
torch.matmul(inputs, weights)

tensor([[-0.0362,  0.4280,  0.2312,  0.0494, -0.7850,  0.1298, -0.1876, -0.0763,
          0.0612,  0.2624],
        [ 0.0912, -1.0788, -0.5828, -0.1245,  1.9788, -0.3271,  0.4728,  0.1924,
         -0.1543, -0.6615],
        [-0.0121,  0.1426,  0.0771,  0.0165, -0.2617,  0.0433, -0.0625, -0.0254,
          0.0204,  0.0875],
        [ 0.0376, -0.4444, -0.2401, -0.0513,  0.8153, -0.1348,  0.1948,  0.0793,
         -0.0636, -0.2725],
        [-0.1378,  1.6296,  0.8804,  0.1880, -2.9892,  0.4942, -0.7142, -0.2907,
          0.2331,  0.9992],
        [ 0.0843, -0.9966, -0.5384, -0.1150,  1.8281, -0.3022,  0.4368,  0.1778,
         -0.1426, -0.6111],
        [ 0.0059, -0.0696, -0.0376, -0.0080,  0.1277, -0.0211,  0.0305,  0.0124,
         -0.0100, -0.0427],
        [ 0.0574, -0.6788, -0.3667, -0.0783,  1.2451, -0.2058,  0.2975,  0.1211,
         -0.0971, -0.4162],
        [ 0.0159, -0.1884, -0.1018, -0.0217,  0.3456, -0.0571,  0.0826,  0.0336,
         -0.0270, -0.1155],
        [ 0.0040, -

Check the time spend to calculate 10 neurons with 784 inputs each:

In [35]:
inputs = torch.randn(10, 28*28)
weights = torch.randn(10, 28*28)

Scratch matmul:

In [36]:
%timeit -n 10 matmul(inputs, weights.T)

1.38 s ± 9.74 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


Python matmul:

In [28]:
%timeit -n 10 inputs @ weights.T

104 µs ± 13.6 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


PyTorch matmul:

In [29]:
%timeit -n 10 torch.matmul(inputs, weights.T)

104 µs ± 16.4 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


### Elementwise operations

Operations (+, -, *, /, >, <, ==)

In [38]:
a = torch.randn(10)
b = torch.randn(10)

In [39]:
(a < b)

tensor([ True, False, False, False, False, False,  True,  True, False, False])

In [40]:
(a < b).float().mean()

tensor(0.3000)

60% of **a** are less than **b**

### Frobenius Norm (Matrix Normalization)

The Frobenius norm, sometimes also called the Euclidean norm (a term unfortunately also used for the vector L^2-norm), is matrix norm of an m×n matrix A defined as the square root of the sum of the absolute squares of its elements. [Wolfram](https://mathworld.wolfram.com/FrobeniusNorm.html)

$$\|A\|_\text{F} = \sqrt{\sum_{i=1}^m \sum_{j=1}^n |a_{ij}|^2} $$

The Frobenius norm can also be considered as a vector norm. 

In [41]:
m = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float32)

In [42]:
def frobeniusNorm(x):
    a = 0.
    for i in range(x.shape[0]):
        for j in range(x.shape[0]):
            a += x[i, j] * x[i, j] #sum
    return a ** (1/2) #sqrt
%time frobeniusNorm(m)

CPU times: user 761 µs, sys: 1.2 ms, total: 1.97 ms
Wall time: 3.65 ms


tensor(16.8819)

or 

In [43]:
%time (m*m).sum().sqrt()

CPU times: user 614 µs, sys: 1.14 ms, total: 1.75 ms
Wall time: 2.91 ms


tensor(16.8819)

### Matrix multiplication optimization

In [44]:
m1 = torch.randn((2,4))
m2 = torch.randn((4,6))

In [45]:
def matmulv2(a, b):
    ar, ac = a.shape
    br, bc = b.shape
    assert ac == br
    c = torch.zeros(ar, bc)
    for i in range(ar):
        for j in range(bc):
            c[i, j] += (a[i, :] * b[:, j]).sum()
    return c

In [46]:
matmulv2(m1, m2)

tensor([[ 1.7821,  2.5351,  1.5442, -1.6701,  3.0583,  1.8754],
        [-0.3904, -2.3032,  0.2099, -0.0456, -3.3459,  1.1390]])

In [47]:
%timeit -n 10 matmulv2(m1, m2)

347 µs ± 40.8 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [48]:
%timeit -n 10 matmul(m1, m2)

1.02 ms ± 107 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


1.39ms vs 673ms

### Broadcasting Rules

Is called broadcasting when Tensor arguments can be expanded to be of equal sizes, without making copies of the data.

Rules:
- each tensor has at least 1 dim
- starting from trailing dimension, the dimensions must *be equals*, one of then 1, or one not exists.

In [49]:
(torch.empty(5,3,4,1) * torch.empty(  3,1,1)).shape

torch.Size([5, 3, 4, 1])

broadcastable, all rules always hold

In [50]:
(torch.empty(5,2,4,1) * torch.empty(  3,1,1)).shape

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

not broadcastable, the 3th dimension not equals or one (2 and 3)

In [51]:
a = torch.tensor([1,2,3,4])
a, a.shape

(tensor([1, 2, 3, 4]), torch.Size([4]))

In [52]:
b = torch.tensor([4,5,6,7])
b, b.shape

(tensor([4, 5, 6, 7]), torch.Size([4]))

How to adds new axis

In [53]:
a[:, None], a[None, :]

(tensor([[1],
         [2],
         [3],
         [4]]),
 tensor([[1, 2, 3, 4]]))

In [54]:
a[:, None] * b[None, :]

tensor([[ 4,  5,  6,  7],
        [ 8, 10, 12, 14],
        [12, 15, 18, 21],
        [16, 20, 24, 28]])

In [55]:
a[:, None] + b[None, :]

tensor([[ 5,  6,  7,  8],
        [ 6,  7,  8,  9],
        [ 7,  8,  9, 10],
        [ 8,  9, 10, 11]])

In [56]:
a = torch.randn(2, 4)
b = torch.randn(4, 2)

In [57]:
a[0, None]

tensor([[ 1.0152,  0.3527, -0.0039,  0.7114]])

In [58]:
b[:, None, 0]

tensor([[-0.6194],
        [-0.5350],
        [-1.2621],
        [ 1.0401]])

In [59]:
(a[0, None] * b[:, None, 0])

tensor([[-0.6287, -0.2184,  0.0024, -0.4406],
        [-0.5431, -0.1887,  0.0021, -0.3806],
        [-1.2812, -0.4451,  0.0050, -0.8978],
        [ 1.0559,  0.3668, -0.0041,  0.7399]])

### Matmul with broadcasting

In [60]:
def matmulv3(a, b):
    ar, ac = a.shape
    br, bc = b.shape
    assert ac == br
    c = torch.zeros(ar, bc)
    for i in range(ar):
        c[i] = (a[i, :, None] * b).sum(dim=0)
    return c

In [61]:
m1.shape, m2.shape

(torch.Size([2, 4]), torch.Size([4, 6]))

In [62]:
x = matmulv3(m1, m2)
x.shape

torch.Size([2, 6])

In [63]:
%timeit matmulv3(m1, m2)

38.5 µs ± 604 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [64]:
a[0, :, None].shape

torch.Size([4, 1])

**a**(4, 1) and **b**(4, 2) dims, now is broadcastable.

In [65]:
a[0, :, None] * b

tensor([[-0.6287, -0.6657],
        [-0.1887,  0.4390],
        [ 0.0050, -0.0034],
        [ 0.7399,  0.2949]])

### Einstein summation

Einstein summation convention is a notational convention that implies summation over a set of indexed terms in a formula, thus achieving notational brevity. [Wikipedia](https://en.wikipedia.org/wiki/Einstein_notation)

There are essentially [three rules](https://mathworld.wolfram.com/EinsteinSummation.html):

1. Repeated indices are implicitly summed over.

2. Each index can appear at most twice in any term.

3. Each term must contain identical non-repeated indices. 

Example:

$$y = \sum_{i = 1}^3 c_i x^i = c_1 x^1 + c_2 x^2 + c_3 x^3$$

is simplified by the convention to:

$$y = c_i x^i$$

In [66]:
# c[i, j] += a[i, k] * b[k, j]
def matmulv4(a, b): return torch.einsum('ik,kj->ij', a, b)

In [67]:
%timeit -n 10 matmulv4(m1, m2)

The slowest run took 8.71 times longer than the fastest. This could mean that an intermediate result is being cached.
60.7 µs ± 77.7 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


### Pytorch Matmul

In [68]:
%timeit -n 10 m1.matmul(m2)

The slowest run took 107.35 times longer than the fastest. This could mean that an intermediate result is being cached.
48.9 µs ± 112 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
