# Questions (01-04 notebooks)

## 1. Write a Python Code to implement a single neuron.

In [184]:
import torch

x = torch.randn(1, 10)
w = torch.randn(1, 10)
b = torch.randn(1)

neuron = x @ w.t() + b
neuron

tensor([[-0.4289]])

## 2. Write the Python code to implement ReLU.

In [166]:
def ReLU(x):
    return x.clamp_min(0.)

ReLU(x), x

(tensor([[1.5722, 0.0000, 0.0000, 0.5082, 0.0000, 0.4540, 0.0000, 0.0000, 0.2060,
          2.1829]]),
 tensor([[ 1.5722, -0.5660, -0.4757,  0.5082, -1.2054,  0.4540, -0.0137, -0.0406,
           0.2060,  2.1829]]))

## 3. Write the Python code for a dense layer in terms of matrix multiplication.

In [187]:
x = torch.randn(1, 10)
w1 = torch.randn(5, 10)
b1 = torch.randn(5)

def linear(x, w, b):
    return x @ w.t() + b

layer1 = ReLU(linear(x, w1, b1))
layer1

tensor([1.1361, 2.2802, 0.4048, 2.3598, 0.0000])

## 4. Write the Python code for a dense layer in plain Python.

**Matrix multiplication:**

$$c_{ij} = a_{i1}b_{1j} + a_{i2}b_{2j} +\cdots + a_{in}b_{nj}= \sum_{k=1}^n a_{ik}b_{kj}$$

**ReLU**

$$f(x) = x^+ = \max(0, x)$$

In [188]:
def ReLU(x):
    r = torch.zeros(x.shape[1])
    for i, e in enumerate(x.squeeze()):
        r[i] = e.item() if e.item() >= 0 else 0.
    return r

def linear(x, w, b):
    return matmul(x, w.t()) + b

def matmul(a, b):
    ar, ac = a.shape[0], a.shape[1]
    br, bc = b.shape[0], b.shape[1]
    c = torch.zeros(ar, bc)
    assert ac==br  
    for i in range(ar):
        for j in range(bc):
            for k in range(br):
                c[i, j] += a[i, k] * b[k, j]
    return c

In [189]:
layer1 = ReLU(linear(x, w1, b1))
layer1

tensor([1.1361, 2.2802, 0.4048, 2.3598, 0.0000])